id = "catppuccin-noctis-icons"
name = "Catppuccin Noctis Icons"
version = "0.1.0"
schema_version = 1
description = "Symbols file icons in the Catppuccin Mocha palette"
authors = ["Rudra Chavda"]
repository = "https://github.com/rudrachavda/zed-icons"
icon_themes = ["icon_themes/catppuccin-noctis-icons-theme.json"]
